#!/usr/bin/env python
"""
file: 2.py
date: Thu Jul 24 09:28:34 EDT 2014
from: Project Euler: http://projecteuler.net
auth: tls
purp: Each new term in the Fibonacci sequence is generated by adding the 
      previous two terms. By starting with 1 and 2, the first 10 terms will be: 
      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
      By considering the terms in the Fibonacci sequence whose values do not 
      exceed four million, find the sum of the even-valued terms.
      Ans: 4613732 on Thu Jul 24 12:51:40 EDT 2014
"""
def sum_fibs():
    max_term= 4000000
    a, b = 0, 1
    tot= 0
    while a < max_term:
        a, b = b, a + b
        if (a % 2) == 0:
            tot += a
            print tot,a
    return [tot,a]

def main():
    print sum_fibs()

if __name__ == "__main__":
    main()
